module.exports = {
  'standard': [
    {place: 'Szpital', roles: ['Pięlęgniarka', 'Lekarz', 'Chirurg', 'Kierownik oddziału', 'Salowa', 'Pacjent', 'Terapeuta']},
    {place: 'Restauracja', roles: ['Szef kuchni', 'Kucharz', 'Właściciel', 'Magda Gessler', 'Gość', 'Gość', 'Bloger kulinarny']},
    {place: 'Statek pasażerski', roles: ['Kucharz', 'Pasażer', 'Pasażer', 'Kapitan', 'Członek załogi', 'Mechanik', 'Barman']},
    {place: 'Zoo', roles: ['Zwiedzający', 'Dyrektor', 'Karmiciel zwierząt', 'Sprzątacz', 'Przewodnik', 'Kierownik ochrony', 'Sprzedawca biletów']},
    {place: 'Łódź podwodna', roles: ['Kapitan', 'Żołnierz', 'Nawigator', 'Radiowec', 'Mechanik', 'Członek załogi', 'Technik']},
    {place: 'Szkoła', roles: ['Uczeń', 'Uczeń', 'Nauczyciel', 'Nauczyciel', 'Sprzątaczka', 'Dyrektor', 'Kierownik', 'Konserwator', 'Psycholog']},
    {place: 'Stacja kosmiczna', roles: ['Astronauta', 'Kosmonauta', 'Astronauta', 'Kosmonauta','Astronauta', 'Tajkonauta', 'Astronauta']},
    {place: 'Teatr', roles: ['Aktor', 'Aktor', 'Aktor', 'Reżyser', 'Scenarzysta', 'Charakteryzator', 'Oświetleniowiec', 'Widz']},
    {place: 'Ambasada', roles: ['Kierownik ochrony', 'Sprzątaczka', 'Pracownik', 'Konsul', 'Księgowa', 'Sekretarz', 'Imigrant']},
    {place: 'Samolot', roles: ['Pasażer', 'Pasażer', 'Stewardessa', 'Pilot', 'Drugi pilot', 'Tajny ochroniarz', 'Biznesmen']},
    {place: 'Bank', roles: ['Kasjer', 'Ochroniarz', 'Klient', 'Konwojent', 'Rabuś', 'Prezes', 'Sprzątaczka', 'Menadżer']},
    {place: 'Kościół', roles: ['Ksiądz', 'Ministrant', 'Kościelny', 'Organista', 'Biskup', 'Wierny', 'Lektor']},
    {place: 'Armia krzyżowców', roles: ['Mnich', 'Pojmany Arab', 'Slużący', 'Biskup', 'Giermek', 'Łucznik', 'Rycerz']},
    {place: 'Korporacja', roles: ['Prezes', 'Korposzczur', 'Sprzątaczka', 'Sekretarka', 'Manager', 'Dyrektor', 'Specjalista PR']},
    {place: 'Stacja polarna', roles: ['Naukowiec', 'Naukowiec', 'Lekarz', 'Badacz', 'Klimatolog', 'Geolog', 'Naukowiec']},
    {place: 'Supermarket', roles: ['Kasjerka', 'Ochroniarz', 'Klient', 'Prezes', 'Kierownik', 'Sprzątaczka', 'Klient']},
    {place: 'Komisariat', roles: ['Policjant', 'Komendant', 'Aspirant', 'Porucznik', 'Ojciec Mateusz', 'Detektyw', 'Konfident']},
    {place: 'Plan filmowy', roles: ['Reżyser', 'Scenarzysta', 'Scenograf', 'Charakteryzator', 'Aktor', 'Operator kamery', 'Dźwiękowiec']},
    {place: 'Baza wojskowa', roles: ['Żołnierz', 'Czołgista', 'Snajper', 'Podporucznik', 'Szeregowy', 'Pułkownik', 'Snajper']},
    {place: 'Kasyno', roles: ['Gracz', 'Kierownik ochrony', 'Prezes', 'Krupier', 'Hostessa', 'Pokerzysta', 'Hazardzista']},
    {place: 'Pociąg pasażerski', roles: ['Konduktor', 'Pasażer', 'Maszynista', 'Mechanik', 'Kobieta z psem', 'Pasażer', 'Biznesmen']},
    {place: 'Statek piratów', roles: ['Pirat', 'Bosman', 'Czarnobrody', 'Majtek', 'Żółtodziób', 'Kpt. Jack Sparrow', 'Szantymen']},
    {place: 'Hotel', roles: ['Gość', 'Gość', 'Recepcjonistka', 'Sprzątaczka', 'Menadżer', 'Odźwierny', 'Właściciel']},
    {place: 'Plaża', roles: ['Plażowicz', 'Fotograf', 'Sprzedawca hotdogów', 'Nudysta', 'Ratownik', 'Polak z parawanem', 'Dziecko']},
  ],
  'fantasy': [
    {place: 'Karczma', roles: ['Brak']},
    {place: 'Zamek', roles: ['Brak']},
    {place: 'Lochy', roles: ['Brak']},
    {place: 'Las Elfów', roles: ['Brak']},
    {place: 'Obóz Orków', roles: ['Brak']},
    {place: 'Pole bitwy', roles: ['Brak']},
    {place: 'Targowisko miejskie', roles: ['Brak']},
    {place: 'Jaskinia pająków', roles: ['Brak']},
    {place: 'Wieża maga', roles: ['Brak']},
    {place: 'Legowisko smoka', roles: ['Brak']},
    {place: 'Przeklęte bagno', roles: ['Brak']},
    {place: 'Klasztor', roles: ['Brak']},
    {place: 'Chata', roles: ['Brak']},
    {place: 'Tajemnicza wyspa', roles: ['Brak']},
    {place: 'Stary młyn', roles: ['Brak']},
    {place: 'Cmentarzysko', roles: ['Brak']},
    {place: 'Kopalnia', roles: ['Brak']},
    {place: 'Statek', roles: ['Brak']},
    {place: 'Stajnia', roles: ['Brak']},
    {place: 'Port', roles: ['Brak']},
    {place: 'Kuźnia', roles: ['Brak']},
    {place: 'Świątynia', roles: ['Brak']},
  ]
};
